services:
  photo-app:
    build: ./sample-app
    ports:
      - "8080:8080"
    networks:
      - selenium-network

  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub:4.25.0
    ports:
      - "4444:4444"
    environment:
      - SE_ROUTER_USERNAME=admin
      - SE_ROUTER_PASSWORD=admin
    networks:
      - selenium-network
    profiles:
      - grid

  # Chrome Nodes (10 instances)
  chrome-node-1:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-2:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-3:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-4:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-5:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-6:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-7:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-8:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-9:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  chrome-node-10:
    image: selenium/node-chrome:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  # Firefox Nodes (10 instances)
  firefox-node-1:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-2:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-3:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-4:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-5:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-6:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-7:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-8:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-9:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  firefox-node-10:
    image: selenium/node-firefox:4.25.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network
    depends_on:
      - selenium-hub
    profiles:
      - grid

  # Test Runner for Grid
  test-runner-grid:
    image: python:3.13-slim
    working_dir: /app
    volumes:
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
      - ./requirements-test.txt:/app/requirements-test.txt
    entrypoint: ["bash", "-c", "pip install -r requirements-test.txt && exec \"$@\"", "--"]
    depends_on:
      - photo-app
      - selenium-hub
    environment:
      - PHOTO_APP_URL=http://photo-app:8080
      - SELENIUM_GRID_URL=http://admin:admin@selenium-hub:4444/wd/hub
    networks:
      - selenium-network
    profiles:
      - grid

  # Original standalone test runner
  chrome:
    image: selenium/standalone-chrome:4.25.0
    ports:
      - "4445:4444"
    environment:
      - SE_START_XVFB=false
    networks:
      - selenium-network
    profiles:
      - test

  test-runner:
    image: python:3.13-slim
    working_dir: /app
    volumes:
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
      - ./requirements-test.txt:/app/requirements-test.txt
    command: >
      bash -c "
        pip install -r requirements-test.txt &&
        python -m pytest tests/test_chrome_app.py -v -s
      "
    depends_on:
      - photo-app
      - chrome
    environment:
      - PHOTO_APP_URL=http://photo-app:8080
      - SELENIUM_URL=http://chrome:4444/wd/hub
    networks:
      - selenium-network
    profiles:
      - test

networks:
  selenium-network:
    driver: bridge